### PR TITLE
fixes undefined push on pending

### PR DESCRIPTION
**Pull request by psheraton**
resolves https://github.com/kellyselden/ember-metrics-adobe-dtm/issues/45

### CODE REVIEW

**Comment by kellyselden** [comment]
This is test only code though right? It doesn't happen in the wild? If that's the case, I think putting an empty pending array on your mocks would be the better option.

**Comment by psheraton** [comment]
What caused this was specifically a bug found when the adobeDTM url was added to an ad-blocker. This somehow caused a condition where the `_satellite` object existed but only had a certain function on it and not the entire object. Then, because of this push on undefined error, the entire app failed to render.

**Comment by kellyselden** [comment]
Ah that makes sense. Thanks for clarifying. If you would add a regression test to this, we can merge.

**Comment by psheraton** [comment]
tests added

**Comment by kellyselden** [comment]
perfect thanks.

**Pull request merged**
